### ISSUE TITLE
nice app

### ISSUE THREAD

**Issue by lordmen99** [ferranfg/midjourney-discord-api-php#1]
Can u add more function, like info,describe,v4 button ,setting,etc..?

**Comment by KENLIEPLAYSPH** [comment]
doesit works on you mine doesn't

**Comment by lordmen99** [comment]
can u send ur token, let me try it

**Comment by lordmen99** [comment]
> doesit works on you mine doesn't

can u send ur token, let me try it

**Comment by KENLIEPLAYSPH** [comment]
it keeps loading the page like since i put it in test.php it doesn't well can do u get the channel in the channel id of midjourney newbie-(number) right?

**Comment by KENLIEPLAYSPH** [comment]
can you show me whats response in yours?

**Comment by lordmen99** [comment]
> can you show me whats response in yours?

i dont have MJ subcription

**Comment by chaoyue007** [comment]
I have imported this library into my test project, do I need to create a Discord channel? Do I need to invite the official MJ bot to my channel in order to use it?

**Comment by ferranfg** [comment]
@lordmen99 sure. Currently it just imagine and upscale the first result, but I'm open to add more functions. What's your use case?

**Comment by lordmen99** [comment]
> @lordmen99 sure. Currently it just imagine and upscale the first result, but I'm open to add more functions. What's your use case?

working fine, but for upscale and other command can add optional. let say after generate, then want U1 or U2 user can send again command, describe,info,setting etc..

**Comment by ferranfg** [comment]
Got it. I've released the library as far I required for my product, but I will gradually add more features in this direction. Thanks for the suggestion.
