### ISSUE TITLE
Not working in php

### ISSUE THREAD

**Issue by Visioweb** [ferranfg/midjourney-discord-api-php#12]
if I launch the script with discord open, on discord bot I see the generated images, while the script continues to run until it times out. How do I get the image returned inside the php script?

**Comment by ferranfg** [comment]
The complete generation takes about 1 minute to complete. If your timeout limit is lower than that, the script will be finished before completing the process. The response will be an object with the URL of the generated image.

**Comment by Visioweb** [comment]
My timeout limit is 6000, but the process continues to run despite the images being generated on discord. It never stops until it times out and returns nothing to me.

**Comment by ferranfg** [comment]
Ok, a few questions about Discord:
- The library currently upscales the first image automatically. Does this proces starts or only the imagine part?
- Does the first message posted on Discord follows the structure: "`{prompt}` - @`{your name}` (fast)"?

![CleanShot 2023-04-25 at 15 34 47](https://user-images.githubusercontent.com/195239/234294288-6c822011-8403-46df-9ca3-84ca1dd6bd92.jpg)

**Comment by Visioweb** [comment]
when i launch the script, after few minutes in discord bot show this message: A cascade of butterfly in a fantastic world --v 5 --v 5 - @Francesco Ingrosso (Waiting to start)

**Comment by ferranfg** [comment]
Yes, but when the imagine stage ends, what does the message says?

**Comment by Visioweb** [comment]
![Screenshot_2023-04-25-20-54-29-89_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/58529746/234375348-be451d71-3527-48ab-b661-2d225c7d23b1.jpg)

**Comment by ferranfg** [comment]
Thanks! The MJ bot replies with different messages and I hadn't seen this.

I will release a new version to address this issue. In the meantime, you can try to edit this line:
https://github.com/ferranfg/midjourney-discord-api-php/blob/main/src/Midjourney.php#L112

**Comment by Visioweb** [comment]
replace it with what?

**Comment by shashwatgokhe** [comment]
> Thanks! The MJ bot replies with different messages and I hadn't seen this.
> 
> I will release a new version to address this issue. In the meantime, you can try to edit this line: https://github.com/ferranfg/midjourney-discord-api-php/blob/main/src/Midjourney.php#L112

I think the button hashes have been changed in the midjourney bot, may be sir you can update the get upscale part of your code.

**Comment by ferranfg** [comment]
I've released a new version (2.0), which should address this issue.
