### ISSUE TITLE
Some accounts, Midjournal, have generated images but have not returned them

### ISSUE THREAD

**Issue by carefreezi** [ferranfg/midjourney-discord-api-php#15]
Some accounts, Midjournal, have generated images but have not returned them
what problem is it？

**Comment by ferranfg** [comment]
@carefreezi can you share the prompt you are using and a `var_dump` of this `$response`?

https://github.com/ferranfg/midjourney-discord-api-php/blob/main/src/Midjourney.php#L130

**Comment by carefreezi** [comment]
Solved the problem because they set some parameters, which resulted in instructions such as - v5- q following, making it impossible to return

**Comment by ferranfg** [comment]
Thanks. I've started to see this is more common than expected, so I will try to fix it from the library. Or at least add some documentation.

**Comment by erikpolder** [comment]
@carefreezi may I ask you how you solved this issue since I am running in the same behavior =) Thanks!

**Comment by ferranfg** [comment]
If you run the `/settings` MJ command, you will see something like: `Current suffix: --v 5.1` (or other params). To get this library running, try to change your settings so your current suffix is empty and add the `--v 5.1` (or the additional params) to your prompt instead.
