### ISSUE TITLE
Query:- How to get private const APPLICATION_ID,DATA_ID,DATA_VERSION for another slash command like /blend etc

### ISSUE THREAD

**Issue by saSharma123** [ferranfg/midjourney-discord-api-php#21]
Hi,

Thank you for providing us with such an API. It is working well, including upscaling. However, now I want to run the /blend and another slash command. How can I obtain the application_id, data_id, and data_version_id? Also, what is the interaction's body data?

I also want to run InsightFaceSwap for my application, and I need to run all the /swapid commands. Could you please provide documentation with screenshots? I am looking forward to your reply. Thank you.

**Comment by ferranfg** [comment]
Hi @saSharma123 I left a brief explanation about how to get the application_id and other values in other issue: https://github.com/ferranfg/midjourney-discord-api-php/issues/22
