### ISSUE TITLE
changed values ID, session_id

### ISSUE THREAD

**Issue by ondraasek** [ferranfg/midjourney-discord-api-php#22]
Hey, these changed yesterday:
    private const DATA_ID = '938956540159881230';

    private const DATA_VERSION = '1077969938624553050';

    private const SESSION_ID = '2fb980f65e5c9a77c96ca01f2c242cf6';
    
any idea how to get them? thank you

**Comment by ferranfg** [comment]
Hi @ondraasek thanks for your notice. I've updated the changed values and released a new version.

I don't know if there is other way, but I get these values opening the Discord's web version and looking at the Network tab from the Developers tools. You will see a request to the /interactions endpoint with all of them:

![CleanShot 2023-06-16 at 11 48 50@2x](https://github.com/ferranfg/midjourney-discord-api-php/assets/195239/7c75fef1-1cbb-4edd-bdf2-4c57bd24a108)

**Comment by ondraasek** [comment]
thanks a lot
