### ISSUE TITLE
Undefined property: stdClass::$guild_id

### ISSUE THREAD

**Issue by pappleweb** [ferranfg/midjourney-discord-api-php#25]
Hi, when I launch on Laravel project your example code, I obtain this error : 

Undefined property: stdClass::$guild_id

Can you help me ?

**Comment by ferranfg** [comment]
Hi @pappleweb most probrably your $channel_id from the `new Midjourney($channel_id, …` is incorrect, as we use this value to get the guild_id.

https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
