### ISSUE TITLE
upscale is not working

### ISSUE THREAD

**Issue by diysoho** [ferranfg/midjourney-discord-api-php#26]
upscale is not working

**Comment by ferranfg** [comment]
The 2 common reasons may be a php timeout or MJ "current suffix" not empty.

To run this library, the current suffix must be empty. If you run the /settings MJ command, you will see something like: "Current suffix: --v 5.1" (or other params). To get this library running, try to change your settings so your current suffix is empty and add the "--v 5.1" (or the additional params) to your prompt instead.
