### ISSUE TITLE
Error to getImagine :\src\Midjourney.php on line 115

### ISSUE THREAD

**Issue by SofianeBoumedine** [ferranfg/midjourney-discord-api-php#27]
Hi, I have an error when I want to get the result of the image generated :
C:\Users\Sosa\Documents\imagegg\imagegg\vendor\ferranfg\midjourney-php\src\Midjourney.php on line 115
[Fri Jul 14 20:42:21 2023] [::1]:58389 [200]: POST /generator.php - Maximum execution time of 60 seconds exceeded in C:\Users\Sosa\Documents\imagegg\imagegg\vendor\ferranfg\midjourney-php\src\Midjourney.php on line 115

**Comment by ferranfg** [comment]
Edit your php.ini to increase your max_execution_time
