### ISSUE TITLE
Should we replace constants? If not, why? Where did you took them?

### ISSUE THREAD

**Issue by ruslan-369** [ferranfg/midjourney-discord-api-php#28]
protected const APPLICATION_ID = '936929561302675456';

protected const DATA_ID = '938956540159881230';

protected const DATA_VERSION = '1118961510123847772';

protected const SESSION_ID = '2fb980f65e5c9a77c96ca01f2c242cf6';

**Comment by ferranfg** [comment]
It's not necessary to change them. They refer to the Midjourney Discord application and similar. 

I explained in this other issue how I get these values https://github.com/ferranfg/midjourney-discord-api-php/issues/22#issuecomment-1594422327
