### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by chaoyue007** [ferranfg/midjourney-discord-api-php#3]
I have imported this library into my test project, do I need to create a Discord channel? Do I need to invite the official MJ bot to my channel in order to use it?

**Comment by ferranfg** [comment]
@chaoyue007 In my testings I've used a new channel and inviting the MJ bot to it. I think it's not mandatory but it's more cleaner https://docs.midjourney.com/docs/invite-the-bot

**Comment by lordmen99** [comment]
better add video demo, how use it.

**Comment by chaoyue007** [comment]
I HAVE used it  ， good

**Comment by lordmen99** [comment]
> I HAVE used it ， good

send me demo please..

**Comment by ferranfg** [comment]
I've added a demo.php file and a small video showing how it works
