### ISSUE TITLE
400 Unknown Channel

### ISSUE THREAD

**Issue by bydbyt-ops** [ferranfg/midjourney-discord-api-php#4]
I get a 400 unknown channel error 

data: { message: 'Unknown Channel', code: 10003 }

**Comment by bydbyt-ops** [comment]
I have a mid journey bot on my own server, and verified if its the right channel id

**Comment by ferranfg** [comment]
@bydbyt-ops from what I've read seems there may be some sort of corruption on this channel/server (not sure if this may apply here tough).

I haven't experienced anything similar or find a way to reproduce it, so I would need your help on here. I would recommend doing some testings to find the reason, like creating a new channel and use that new ID or (if you have the chance) creating a new server and install there the mj bot.

Thanks!
