### ISSUE TITLE
Now we can generate images, but we cannot output them

### ISSUE THREAD

**Issue by Sanyela** [ferranfg/midjourney-discord-api-php#5]

**Comment by ferranfg** [comment]
Currently the only output is `$message->upscaled_photo_url` which returns the URL of the first image upscaled to this prompt. There is small demo here https://github.com/ferranfg/midjourney-discord-api-php/blob/main/img/demo.gif

You can take this value and use it inside an img tag, for instance: `<img src="<?php echo $message->upscaled_photo_url; ?>" />` to display the generated image.

**Comment by Sanyela** [comment]
But soon after the generation is completed, the page status is directly 502
![image](https://user-images.githubusercontent.com/119792728/233848409-03eaa051-b10c-4f2a-b6ed-d7063ecbe2dd.png)

**Comment by Sanyela** [comment]
它并不能返回出图片
![image](https://user-images.githubusercontent.com/119792728/233848438-bb7fe17d-031e-48cc-ad8f-62d3b810a495.png)
