### ISSUE TITLE
upscale issue

### ISSUE THREAD

**Issue by lordmen99** [ferranfg/midjourney-discord-api-php#6]
i have try generate images, its working good. but for upscale let say U1, its seem not direct execute. better make it after get response success generate, its direct upscale U1

**Comment by ferranfg** [comment]
The next release will add a method to choose which option to upscale.
Currently it was based on my use-case, so I will extend the library.

**Comment by ferranfg** [comment]
I've released a new version (2.0), which should address this issue.
